version: '3.9'

services:
  php:
    container_name: croppa-php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www/html/croppa
  web:
    container_name: croppa-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html/croppa
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./src:/app
    command: composer install
    depends_on:
      - php